In [ ]:
'''Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.'''

In [34]:
import pandas as pd
import numpy as np

In [35]:
x = np.array([1,2,3,4,5])

In [36]:
np.vander(x)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [37]:
np.vander(x,3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [38]:
np.vander(x,3,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

In [39]:
N=3

In [52]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]], dtype=int32)

In [51]:
np.column_stack([x**(N-1-i) for i in range(N-1,-1,-1)])

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]], dtype=int32)

In [ ]:
'''Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.'''

In [53]:
y = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [57]:
n=len(y) 
k=3
a = n-k+1
a

11

In [92]:
for i in range(a):
    SMA = (y[i:i+3].sum())/k
    print('Y'+ str([i+1]) + ':'+ str(SMA.round(2)))


Y[1]:5.0
Y[2]:4.67
Y[3]:5.67
Y[4]:6.67
Y[5]:9.67
Y[6]:28.67
Y[7]:49.33
Y[8]:72.67
Y[9]:84.0
Y[10]:93.33
Y[11]:116.33
